-- Schema: Soccer (3NF)
CREATE SCHEMA IF NOT EXISTS soccer;
SET search_path TO soccer, public;

-- 1) COUNTRY
CREATE TABLE IF NOT EXISTS country (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    CONSTRAINT uq_country_name UNIQUE (name),
    CONSTRAINT ck_country_name CHECK (length(name) > 0)
);

-- 2) LEAGUE
CREATE TABLE IF NOT EXISTS league (
    id INTEGER PRIMARY KEY,
    country_id INTEGER NOT NULL REFERENCES country(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    name TEXT NOT NULL,
    CONSTRAINT uq_league_country_name UNIQUE (country_id, name),
    CONSTRAINT ck_league_name CHECK (length(name) > 0)
);

-- Index helpful when filtering by country
CREATE INDEX IF NOT EXISTS idx_league_country ON league(country_id);

-- 3) TEAM
-- Notes:
--   - team_api_id is the identifyier we use on match/attributes.
--   - team_fifa_api_id can be null or duplicate.
--     Index use only when the value is NOT NULL
CREATE TABLE IF NOT EXISTS team (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_api_id INTEGER NOT NULL,
    team_fifa_api_id INTEGER NULL,
    team_long_name TEXT NOT NULL,
    team_short_name TEXT NULL,
    CONSTRAINT uq_team_api UNIQUE (team_api_id),
    CONSTRAINT ck_team_names CHECK (length(team_long_name) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_team_fifa
    ON team(team_fifa_api_id)
    WHERE team_fifa_api_id IS NOT NULL;

-- Search by name
CREATE INDEX IF NOT EXISTS idx_team_long_name ON team(team_long_name);

-- 4) PLAYER
CREATE TABLE IF NOT EXISTS player (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_api_id INTEGER NOT NULL,
    player_name TEXT,
    birthday DATE,
    height_cm NUMERIC(5,1),
    weight_kg NUMERIC(5,1),
    CONSTRAINT uq_player_api UNIQUE (player_api_id),
    CONSTRAINT ck_height_cm CHECK (height_cm IS NULL OR (height_cm BETWEEN 120 AND 230)),
    CONSTRAINT ck_weight_kg CHECK (weight_kg IS NULL OR (weight_kg BETWEEN 45 AND 130))
);

-- Search by player's name
CREATE INDEX IF NOT EXISTS idx_player_name ON player(player_name);

-- 5) PLAYER_ATTRIBUTES
-- Notes:
--   Range from 0-99
CREATE TABLE IF NOT EXISTS player_attributes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_api_id INTEGER NOT NULL REFERENCES player(player_api_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    date TIMESTAMP NOT NULL,
    overall_rating SMALLINT,
    potential SMALLINT,
    sprint_speed SMALLINT,
    acceleration SMALLINT,
    finishing SMALLINT,
    passing SMALLINT,
    dribbling SMALLINT,
    long_shots SMALLINT,
    preferred_foot TEXT NULL,
    CONSTRAINT ck_pref_foot CHECK (preferred_foot IS NULL OR preferred_foot IN ('left','right')),
    CONSTRAINT ck_attr_0_99 CHECK (
        (overall_rating IS NULL OR overall_rating BETWEEN 0 AND 99) AND
        (potential IS NULL OR potential BETWEEN 0 AND 99) AND
        (sprint_speed IS NULL OR sprint_speed BETWEEN 0 AND 99) AND
        (acceleration IS NULL OR acceleration BETWEEN 0 AND 99) AND
        (finishing IS NULL OR finishing  BETWEEN 0 AND 99) AND
        (passing IS NULL OR passing BETWEEN 0 AND 99) AND
        (dribbling IS NULL OR dribbling BETWEEN 0 AND 99) AND
        (long_shots IS NULL OR long_shots BETWEEN 0 AND 99)
    )
);

-- Index for performance in specify range date
CREATE INDEX IF NOT EXISTS idx_playerattr_player_date
    ON player_attributes(player_api_id, date);

CREATE INDEX IF NOT EXISTS idx_playerattr_overall
    ON player_attributes(overall_rating);

-- 6) TEAM_ATTRIBUTES
-- Notes:
--   Range 0-99

CREATE TABLE IF NOT EXISTS team_attributes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_api_id INTEGER NOT NULL REFERENCES team(team_api_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    date TIMESTAMP NOT NULL,
    buildUpPlaySpeed SMALLINT,
    chanceCreationPassing SMALLINT,
    chanceCreationShooting SMALLINT,
    defencePressure SMALLINT,
    defenceAggression SMALLINT,
    CONSTRAINT ck_team_attr_0_99 CHECK (
        (buildUpPlaySpeed IS NULL OR buildUpPlaySpeed BETWEEN 0 AND 99) AND
        (chanceCreationPassing IS NULL OR chanceCreationPassing BETWEEN 0 AND 99) AND
        (chanceCreationShooting IS NULL OR chanceCreationShooting BETWEEN 0 AND 99) AND
        (defencePressure IS NULL OR defencePressure BETWEEN 0 AND 99) AND
        (defenceAggression IS NULL OR defenceAggression BETWEEN 0 AND 99)
    )
);

CREATE INDEX IF NOT EXISTS idx_teamattr_team_date
    ON team_attributes(team_api_id, date);